-- Enable UUID extension if not enabled (Supabase has this enabled by default in extensions schema, but good practice to ensure)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create customers table
CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255),
    tags TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
    amount NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create campaigns table
CREATE TABLE IF NOT EXISTS campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    channel VARCHAR(50) NOT NULL, -- 'whatsapp' or 'sms'
    message TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING', -- 'PENDING', 'SENT', 'FAILED'
    guardrail_skipped INTEGER DEFAULT 0, -- Number of recipients skipped by 24h contact guardrail
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create campaign_messages table
CREATE TABLE IF NOT EXISTS campaign_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID REFERENCES campaigns(id) ON DELETE CASCADE,
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
    message_id VARCHAR(255), -- Unique ID generated by the channel-service
    status VARCHAR(50) DEFAULT 'QUEUED', -- 'QUEUED', 'SENT', 'DELIVERED', 'OPENED', 'FAILED'
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_messages ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public (anon) access for this demo CRM (auth is out of scope)
DROP POLICY IF EXISTS "Allow anon access to customers" ON customers;
CREATE POLICY "Allow anon access to customers" ON customers
    FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon access to orders" ON orders;
CREATE POLICY "Allow anon access to orders" ON orders
    FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon access to campaigns" ON campaigns;
CREATE POLICY "Allow anon access to campaigns" ON campaigns
    FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon access to campaign_messages" ON campaign_messages;
CREATE POLICY "Allow anon access to campaign_messages" ON campaign_messages
    FOR ALL TO anon USING (true) WITH CHECK (true);

